### ISSUE TITLE
Error while trying to access completionProvider.

### ISSUE THREAD

**Issue by ruderngespra** [vscode-langservers/vscode-html-languageserver-bin#6]
I use lsp-mode for Emacs and everything works perfectly except for the auto-completion.

Inside Emacs I can start the server via the "lsp"-command. But when I try to trigger auto-completion I get the following error messages printed into my lsp-log:

```
<<<< html-ls:30540
{
  "jsonrpc": "2.0",
  "method": "window/logMessage",
  "params": {
    "type": 1,
    "message": "Error while computing completions for file:///home/janko/tmp22/asfasdf.html: Cannot read property '0' of null\nTypeError: Cannot read property '0' of null\n    at /home/janko/.config/yarn/global/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:92:153"
  }
}
Error while computing completions for file:///home/janko/tmp22/asfasdf.html: Cannot read property '0' of null
TypeError: Cannot read property '0' of null
    at /home/janko/.config/yarn/global/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:92:153
```

Apart from the auto-completion, the server seems to be working fine. lsp-describe-session gives me the following tree:

```
[-] /home/janko/tmp22/
 `-[-] html-ls:30540
    |-[-] Buffers
    |  `-[+] asfasdf.html
    `-[-] Capabilities
       |-[X] foldingRangeProvider: t
       |-[X] colorProvider:
       |-[X] referencesProvider: t
       |-[-] signatureHelpProvider:
       |  `-[X] triggerCharacters: [(]
       |-[X] definitionProvider: t
       |-[X] documentSymbolProvider: t
       |-[-] documentLinkProvider:
       |  `-[X] resolveProvider: nil
       |-[X] documentRangeFormattingProvider: nil
       |-[X] documentHighlightProvider: t
       |-[X] hoverProvider: t
       |-[-] completionProvider:
       |  |-[X] triggerCharacters: [. : < " = /]
       |  `-[X] resolveProvider: t
       `-[X] textDocumentSync: 1
```

I can reproduce the error with any newly created html-server and any new root file.

There are no similar issues either with the vscode-css-server nor the cscode-typescript-server which are the other ones I tried for now.

Any suggestions on how to further investigate this issue would be gladly appreciated!

**Comment by ruderngespra** [comment]
Turns out it was a bug in lsp-mode, the issue has been fixed:
https://github.com/emacs-lsp/lsp-mode/issues/752
